# Generated by Django 2.2.4 on 2019-10-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20191029_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banned_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
