# Generated by Django 2.2.5 on 2019-10-30 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_auto_20191029_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Post'),
        ),
    ]
