# Generated by Django 2.2.4 on 2019-11-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
