# Generated by Django 2.2.4 on 2019-11-27 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='time_line_view',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
