# Generated by Django 2.2.4 on 2019-11-27 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_auto_20191126_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='curr_time_line_view',
            new_name='time_line_view',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prev_time_line_view',
        ),
    ]
