# Generated by Django 2.2.4 on 2019-11-27 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_auto_20191126_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='time_line_view',
            new_name='curr_time_line_view',
        ),
        migrations.AddField(
            model_name='user',
            name='prev_time_line_view',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
