# Generated by Django 2.2.4 on 2019-11-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0029_auto_20191130_1405'),
        ('blogs', '0025_auto_20191127_0100'),
    ]

    operations = [
    ]
